export const salaat = [
  {
    id: 1,
    name: 'Ibrahimi',
    nameUrdu: 'ابراہیمی',
    img: require('../assets/SalaatImgs/Ibrahimi.jpg'),
    reads: 12442,
    narration:'  حضرت کعب بن عجرہ   کابیان ہے کہ حضورﷺکی خدمت میں عرض کی گئ کہ یارسول اللہﷺ!آپ پر سلام بھیجنےکا طریقہ توہم اچھی طرح جان گئےلیکن صلوٰۃکس طرح بھیجیں توفرمایا یوں کہو'
  },
  {
    id: 2,
    name: 'Ibrahimi Bukhari',
    img: require('../assets/SalaatImgs/Imambukhari.jpg'),
    reads: 12442,
    narration:''
  },
  {
    id: 3,
    name: 'Ibrahimi Muslim',
    img: require('../assets/SalaatImgs/imammuslim.jpg'),
    reads: 12442,
    narration:''
  },
  {
    id: 4,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi Naqshbandi',
    img: require('../assets/SalaatImgs/imamtirmazi.jpg'),
    reads: 12442,
    narration:''
  },
  {
    id: 5,
    name: 'Ibrahimi',
    img: require('../assets/SalaatImgs/imamabudawood.jpg'),
    reads: 12442,
    narration:''
  },
  {
    id: 6,
    name: 'Ibrahimi Bukhari',
    img: require('../assets/SalaatImgs/imamibnemaja.jpg'),
    reads: 12442,
    narration:''
  },
  {
    id: 7,
    name: 'Ibrahimi Muslim',
    img: require('../assets/SalaatImgs/imamnasai.jpg'),
    reads: 12442,
  },
  {
    id: 8,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/imamkabbinujrah.jpg'),
    reads: 12442,
  },
  {
    id: 9,
    name: 'Ibrahimi',
    img: require('../assets/SalaatImgs/imamnamiri.jpg'),
    reads: 12442,
  },
  {
    id: 10,
    name: 'Ibrahimi Bukhari',
    img: require('../assets/SalaatImgs/imamtabari.jpg'),
    reads: 12442,
  },
  {
    id: 11,
    name: 'Ibrahimi Muslim',
    img: require('../assets/SalaatImgs/imambehqi.jpg'),
    reads: 12442,
  },
  {
    id: 12,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/imamulalameen.jpg'),
    reads: 12442,
  },
  {
    id: 13,
    name: 'Ibrahimi',
    img: require('../assets/SalaatImgs/imamulsiddiqueen.jpg'),
    reads: 12442,
  },
  {
    id: 14,
    name: 'Ibrahimi Bukhari',
    img: require('../assets/SalaatImgs/imamunnabiyeen.jpg'),
    reads: 12442,
  },
  {
    id: 15,
    name: 'Ibrahimi Muslim',
    img: require('../assets/SalaatImgs/imamulmutaqeen.jpg'),
    reads: 12442,
  },
  {
    id: 16,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/imamulmursaleen.jpg'),
    reads: 12442,
  },
  {
    id: 17,
    name: 'Ibrahimi',
    img: require('../assets/SalaatImgs/imamulkhair.jpg'),
    reads: 12442,
  },
  {
    id: 18,
    name: 'Ibrahimi Bukhari',
    img: require('../assets/SalaatImgs/jamaeaibrahimi.jpg'),
    reads: 12442,
  },
  {
    id: 19,
    name: 'Ibrahimi Muslim',
    img: require('../assets/SalaatImgs/makhsoosbilsharf.jpg'),
    reads: 12442,
  },
  {
    id: 20,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/unhatulmomineen.jpg'),
    reads: 12442,
  },
  {
    id: 21,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/ahlebait.jpg'),
    reads: 12442,
  },
  {
    id: 22,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/zuriyat.jpg'),
    reads: 12442,
  },
  {
    id: 23,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/nabierehmat.jpg'),
    reads: 12442,
  },
  {
    id: 24,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/khairulanaam.jpg'),
    reads: 12442,
  },
  {
    id: 25,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/syedussaqalain.jpg'),
    reads: 12442,
  },
  {
    id: 26,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/syedulkonain.jpg'),
    reads: 12442,
  },
  {
    id: 27,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/nabiemubashir.jpg'),
    reads: 12442,
  },
  {
    id: 28,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Syed-ul-Rusul.jpg'),
    reads: 12442,
  },
  {
    id: 29,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Rusul-e-Ameen.jpg'),
    reads: 12442,
  },
  {
    id: 30,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Rusul-e-Mukarram-1.jpg'),
    reads: 12442,
  },
  {
    id: 31,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Sahib-e-Wahi.jpg'),
    reads: 12442,
  },
  {
    id: 32,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Quiad-e-Ambiya.jpg'),
    reads: 12442,
  },
  {
    id: 33,
    name: 'Sheikh Khalid Naqshbandi Naqshband',
    img: require('../assets/SalaatImgs/Sahib-e-Laolaak.jpg'),
    reads: 12442,
  },
  {
    id: 34,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Sahib-e-Muqaam.jpg'),
    reads: 12442,
  },
  {
    id: 35,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Khatam-un-Nabiyeen.jpg'),
    reads: 12442,
  },
  {
    id: 36,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Khair-al-Bariya.jpg'),
    reads: 12442,
  },
  {
    id: 37,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Nabi-al-Ummi.jpg'),
    reads: 12442,
  },
  {
    id: 38,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Muhammad-Arabi.jpg'),
    reads: 12442,
  },
  {
    id: 39,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Ibn-al-Umer.jpg'),
    reads: 12442,
  },
  {
    id: 40,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Dawat-Nama.jpg'),
    reads: 12442,
  },
  {
    id: 41,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Khizri.jpg'),
    reads: 12442,
  },
  {
    id: 42,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Hazaara.jpg'),
    reads: 12442,
  },
  {
    id: 43,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Nemat-e-Uzma.jpg'),
    reads: 12442,
  },
  {
    id: 44,
    name: 'Sheikh Khalid NaqshbandiNaqshbandi',
    img: require('../assets/SalaatImgs/Qaseeda-e-Busiri.jpg'),
    reads: 12442,
  },
  {
    id: 45,
    name: 'Sheikh Khalid Naqshbandi',
    img: require('../assets/SalaatImgs/Taj.jpg'),
    reads: 12442,
  },
  {
    id: 46,
    name: 'Sheikh Khalid Naqshbandi',
    reads: 12442,
  },
];